<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS008_Shopify_Verify_Store_Front - 2</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>5078cdbc-81e6-4e52-9833-16f4ad0f8379</testSuiteGuid>
   <testCaseLink>
      <guid>46157cc1-7353-40cb-99c3-a1535e55a61a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Shopify/TC010_Verify Store Front</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>5844ef1f-15b1-4870-b410-6f510345314b</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>2</value>
         </iterationEntity>
         <testDataId>Data Files/UatData/AR-Basic-StoreData-UAT</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>5844ef1f-15b1-4870-b410-6f510345314b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>store_name</value>
         <variableId>a1646514-2986-41d6-8399-b35f0c88d9a1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5844ef1f-15b1-4870-b410-6f510345314b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>store_password</value>
         <variableId>07807bfa-9102-4450-a470-8bfd7c255e5a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30d3cf3f-1174-4247-9742-b37282f94d39</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69cdaa90-27ef-41c2-a2cd-1456af0b38ee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3ff64bf-a4f5-4272-b024-79c80ac88f9a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d783a23-efd0-4172-9a33-aa715ded1d9f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8c63316-c6d5-4853-9428-a37be6a04aa9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0a05ee4-3c9c-46e4-8467-a173119b3d10</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad458330-1862-47af-9b7e-8ff843558fd0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b01af51d-53ab-4bd6-b8e0-957021acff3d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48e1ff32-53a8-4e56-9b52-b94ec87a7cc7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c887f19-e532-4845-91e5-4ede729cb7a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51456421-e070-4b71-981f-7e92c6d1f986</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe0a9686-de99-41bd-9851-6eacd402dbc8</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
